### ISSUE TITLE
Error when connecting a client

### ISSUE THREAD

**Issue by 2n2u** [MJ-meo-dmt/netPanda#1]
C:\Python27\python.exe C:/Users/Andre/Desktop/testing/netPanda-master/src/server.py
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
Server: Listener & Readers Started!
Server: Active!
Waiting for connections....
:ShowBase(warning): run() is deprecated, use base.run() instead
Server: New Connection from - 127.0.0.1
Server: New client connected - TestClient
Server: New Player  TestClient
Traceback (most recent call last):
  File "C:/Users/Andre/Desktop/testing/netPanda-master/src/server.py", line 62, in update
    self.serverState.update()
  File "C:\Users\Andre\Desktop\testing\netPanda-master\src\server\serverState.py", line 59, in update
    self.broadcastUpdates()
  File "C:\Users\Andre\Desktop\testing\netPanda-master\src\server\serverState.py", line 81, in broadcastUpdates
    self.networkMgr.command.broadcastUpdates(clId, clState, clInputOldTime, conn)
  File "C:\Users\Andre\Desktop\testing\netPanda-master\src\server\commands.py", line 92, in broadcastUpdates
    pkg.addUint64(_clState.t)
TypeError: add_uint64() argument must be integer<K>, not float
:task(error): Exception occurred in PythonTask update
Traceback (most recent call last):
  File "C:/Users/Andre/Desktop/testing/netPanda-master/src/server.py", line 69, in <module>
    run()
  File "C:\Panda3D-1.9.1\direct\showbase\ShowBase.py", line 54, in legacyRun
    builtins.base.run()
  File "C:\Panda3D-1.9.1\direct\showbase\ShowBase.py", line 2984, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.9.1\direct\task\Task.py", line 510, in run
    self.step()
  File "C:\Panda3D-1.9.1\direct\task\Task.py", line 467, in step
    self.mgr.poll()
  File "C:/Users/Andre/Desktop/testing/netPanda-master/src/server.py", line 62, in update
    self.serverState.update()
  File "C:\Users\Andre\Desktop\testing\netPanda-master\src\server\serverState.py", line 59, in update
    self.broadcastUpdates()
  File "C:\Users\Andre\Desktop\testing\netPanda-master\src\server\serverState.py", line 81, in broadcastUpdates
    self.networkMgr.command.broadcastUpdates(clId, clState, clInputOldTime, conn)
  File "C:\Users\Andre\Desktop\testing\netPanda-master\src\server\commands.py", line 92, in broadcastUpdates
    pkg.addUint64(_clState.t)
TypeError: add_uint64() argument must be integer<K>, not float

Process finished with exit code 1

I don't know why it's passing a float.

**Comment by MJ-meo-dmt** [comment]
Hi, Hmm this code is so so so so so * 99999 old... And I dropped it long ago, I should and will remove this code from here because its just so bugged...

The issue is in the commands.py Line 92: pkg.addUint64(_clState.t) you could make it pkg.addFloat32(_clState.t) i think... or you have to change the .t in the client state class.

Here is the main cause of it.
self.inputCmds.oldTime = float(0.0)#'+infinity')
It should be +infinity
But I had some issue with that and never really fixed it.

What I could suggest is to look at the grim_net code, its much cleaner, and as far as I can remember more stable and it contains most of the things from netPanda, but in a better way.  Again its all just old code that weren't finished.

Sorry about that :)  On a side note I don't use panda3d anymore.
Here is the grim_net code: https://github.com/grimfang/grim_net/tree/master/src

**Comment by 2n2u** [comment]
Thanks for the quick answer, will try grim_net then :)

**Comment by MJ-meo-dmt** [comment]
Awesome no problem.  Sorry about that though :)
You can always join #grimfang channel on freenode during the day. GMT+2 /+1.  And maybe I can help here and there.

**Comment by 2n2u** [comment]
I was looking for a network "module" for Panda3d and I stumbled upon this. I'll probably show on #grimfang :)
Thanks for your help!
